# Generated by Django 4.2 on 2024-08-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_alter_message_options_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_subject_message", "can_view_subject_message"),
                    ("can_view_subject_text", "can_view_subject_text"),
                ],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
