# Generated by Django 4.2 on 2024-08-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_subject_message", "can_view_subject_message"),
                    ("can_view_text_message", "can_view_text_message"),
                ],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
