# Generated by Django 4.2 on 2024-08-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_settings_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={
                "permissions": [("can_disabled_mailing", "can_disabled_mailing")],
                "verbose_name": "настройки",
                "verbose_name_plural": "настройки",
            },
        ),
    ]
