# Generated by Django 4.2 on 2024-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_content_alter_blog_preview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(default=" "),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_previews/"),
        ),
    ]
